---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/ehussong/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - git
  - github/gh/gh
  - gnu-tar
  - libevent
  - sqlite
  - ssh-copy-id
  - readline
  - openssl
  - wget
  - zsh-history-substring-search
  - SoMuchForSubtlety/tap/f1viewer
  - mas
  - mpv
  - tldr

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - SoMuchForSubtlety/tap


homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - handbrake
  - calibre
  - iridium
  - parallels
  - parallels-toolbox
  - 1password
  - affinity-photo
  - airtable
  - alfred
  - balenaetcher
  - bartender
  - cheatsheet
  - daisydisk
  - deepl
  - devonthink
  - devonagent
  - discord
  - element
  - ultimate
  - fantastical
  - freedom
  - github
  - gog-galaxy
  - hazel
  - hook
  - istat-menus
  - keyboard-maestro
  - kobo
  - krisp
  - league-of-legends
  - little-snitch
  - microsoft-teams
  - mullvadvpn
  - musicbrainz-picard
  - openaudible
  - parsec
  - plexamp
  - pocket-casts
  - prowritingaid
  - rescuetime
  - roon
  - royal-tsx
  - scrivener
  - signal
  - skim
  - quassel-client
  - soundsource
  - steam
  - teamviewer
  - the-unarchiver
  - thebrain
  - tidal
  - transmission
  - visual-studio-code
  - vivaldi
  - zenmap
  - zoom
  - zotero

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
